### ISSUE TITLE
Error: ENOENT: no such file or directory, open [...]

### ISSUE THREAD

**Issue by julioCROS** [eliabefranca/eliabot#10]
Boa tarde, ao tentar executar o bot, o mesmo não pode ser executado por um erro em "config.ts", no qual acredito que você tenha deletado/trocado o diretório do 'database'.

A pasta 'database' agora se encontra em **'src/database'**, eu tentei mudar aqui para **'../src/database/models'** mas mesmo assim não reconhece o diretório, apenas passando todo o diretório no estilo **'C:/.../.../'** ou criando o diretório **'/db'** com os arquivos de **'/src/database/models'**

Segue imagem:
![](https://i.ibb.co/FqnKMYN/db-Folder-ERROR.png)

**Comment by eliabefranca** [comment]
@julioCROS Acabei de corrigir aqui, consegue testar de novo?

**Comment by julioCROS** [comment]
@Eliabe45 
Boa, agora foi aqui, vlw.
