### ISSUE TITLE
O que você acha de uma logo com estilinho cartoon?

### ISSUE THREAD

**Issue by Agronault** [eliabefranca/eliabot#5]
Eu consigo mexer com umas paradas de design tbm, aí tava pensando se você não queria q eu fizesse uma logo pro bot, deixarei uma sugestão abaixo, me diz oq vc acha da ideia.

PS: Se preferir uma abordagem diferente, posso testar outras coisas tbm

![image](https://user-images.githubusercontent.com/31781535/126043681-a65d3058-815b-4cbe-b46b-0cf308e72281.png)

![Component 805](https://user-images.githubusercontent.com/31781535/126043755-67d3d6f1-f1e0-4ce3-96bb-7f735d9f1907.png)

**Comment by eliabefranca** [comment]
Eu gostei muito, achei massa demais. Talvez pode ser uma boa pra colocar no painel, ou usar dentro de alguns comandos etc.
Eu  pessoalmente ainda prefiro a logo atual, e a pessoa que fez também ficaria triste se eu tirasse haha, mas ela precisa de uma retrabalhada tb...

Vou fazer uma votação e deixar o povo escolher, isso já abre porta pra botar um comando de votação :smile: .
Você consegue enviar outra versão com a tom da pele do robô mais clara um pouco? Tava pensando em #cc8566
Dá pra deixar só a primeira letra em maiúsculo tb? só pra ver como fica.

**Comment by Agronault** [comment]
@Eliabe45 
Modifiquei como comentou.
PS: a votação seria uma boa mesmo, vou colocar no TO-DO aqui


![Component 805 (1)](https://user-images.githubusercontent.com/31781535/126054036-488d5698-917d-4a14-8f49-b5be863fe337.png)

**Comment by eliabefranca** [comment]
@Agronault boa, achei que ficou legal. Assim que ficar pronto esse comando vou botar pro provo escolher :smile:
